export interface Article {
  id: string;
  title: string;
  category: 'climate' | 'living' | 'guide';
  readTime: string;
  summary: string;
  content: string[];
}

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export const ARTICLES: Article[] = [
  {
    id: 'intro-to-carbon-footprint',
    title: 'Understanding Your Carbon Footprint',
    category: 'climate',
    readTime: '4 min read',
    summary: 'What is a carbon footprint, why does it matter, and how do our everyday actions contribute to greenhouse gases?',
    content: [
      'A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. The average global carbon footprint is close to 4 tons per person annually. However, to avoid a 2°C rise in global temperatures, the average footprint needs to drop under 2 tons by 2050.',
      'Our daily choices directly influence this number. When we drive gasoline cars, eat meat, heat our homes with fossil fuels, or purchase heavily packaged goods, we trigger carbon emissions. Calculating and tracking these actions is the first step toward lowering our footprint.',
      'By focusing on high-impact areas like switching to public transit, buying local food, and reducing electricity use, we can significantly reduce our negative climate footprint.'
    ]
  },
  {
    id: 'sustainable-diet-choices',
    title: 'The Climate Impact of Food Habit Choices',
    category: 'living',
    readTime: '5 min read',
    summary: 'How does food production affect the climate, and how can transitioning to a plant-forward diet reduce your footprint?',
    content: [
      'Food accounts for over a quarter (26%) of global greenhouse gas emissions. Livestock farming, deforestation for agriculture, and food waste in landfills are the three largest drivers of diet-related carbon footprints.',
      'Animal products generally have a much higher footprint than plant-based alternatives. Producing 1kg of beef results in about 60kg of greenhouse gases, while 1kg of peas produces less than 1kg. Simply substituting beef or dairy for plant-based meals a few times a week can dramatically cut your footprint.',
      'Food waste is another huge contributor. If food waste were a country, it would be the third-largest emitter in the world. Plan meals carefully, compost organic waste, and eat leftovers to minimize food waste!'
    ]
  },
  {
    id: 'energy-efficiency-guide',
    title: 'Home Energy Optimization Guide',
    category: 'guide',
    readTime: '6 min read',
    summary: 'Practical tips to reduce your electricity consumption, lower utility bills, and shift toward clean energy sources.',
    content: [
      'The electricity and heat we consume in our homes are responsible for a large share of urban carbon emissions. Reducing heating/cooling demands, switching to energy-efficient appliances, and sourcing renewable energy can cut emissions by up to 80%.',
      'Start with low-hanging fruit: replace all incandescent light bulbs with LEDs (which use 75% less energy), unplug idle electronics (phantom load accounts for 10% of household electricity), and set thermostats 2 degrees lower in winter and 2 degrees higher in summer.',
      'Consider long-term improvements: install solar panels or contact your utility provider to switch your home to a 100% renewable grid plan. This redirects your footprint from fossil fuel generation to zero-emission wind and solar.'
    ]
  },
  {
    id: 'eco-transport-tips',
    title: 'Eco-Friendly Commuting Strategies',
    category: 'guide',
    readTime: '4 min read',
    summary: 'Ditch the solo car drive and explore low-carbon transit methods: active transit, shared rides, and electric vehicles.',
    content: [
      'Transportation is the largest contributor to carbon emissions in many developed countries, with passenger cars accounting for over half of this total. A typical passenger vehicle emits about 4.6 metric tons of CO2 per year.',
      'The most effective way to reduce transport emissions is to drive less. Walking, bicycling, or using electric scooters for trips under 5km produces zero emissions and improves cardiovascular health. For longer commutes, public trains and buses cut emissions per passenger by 60% to 80% compared to single-occupancy driving.',
      'If driving is necessary, carpooling distributes emissions among multiple passengers, and transitioning to an Electric Vehicle (EV) charged on a clean grid reduces lifecycle transit emissions to a fraction of a conventional gasoline car.'
    ]
  }
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'Which sector contributes the most to global greenhouse gas emissions?',
    options: ['Transportation', 'Agriculture & Land Use', 'Energy (Electricity & Heat)', 'Manufacturing & Industry'],
    correctIndex: 2,
    explanation: 'Energy production (electricity, heat, and fuel combustion) represents approximately 73% of global emissions, making it the primary driver of climate change.'
  },
  {
    id: 'q2',
    question: 'How much lower is the carbon footprint of a typical vegan diet compared to a heavy meat-based diet?',
    options: ['About 10% lower', 'About 30% lower', 'About 50% to 70% lower', 'No significant difference'],
    correctIndex: 2,
    explanation: 'Transitioning to a plant-based or vegan diet reduces individual food-related emissions by 50% to 70% due to the high land, feed, and methane emissions associated with raising livestock.'
  },
  {
    id: 'q3',
    question: 'What does "Phantom Load" (or standby power) refer to in home energy consumption?',
    options: [
      'Power drawn by appliances that are plugged in but turned off',
      'Power surges caused by lightning strikes',
      'Energy stored in home solar batteries',
      'Electricity used by heavy laundry dryers'
    ],
    correctIndex: 0,
    explanation: 'Phantom load is the energy consumed by electronic devices while they are plugged in but inactive. It accounts for up to 10% of residential electricity use.'
  },
  {
    id: 'q4',
    question: 'Which of the following transit modes has the lowest carbon footprint per passenger-kilometer?',
    options: ['Gasoline Passenger Car', 'Commercial Flight', 'Electric Train', 'City Transit Bus'],
    correctIndex: 2,
    explanation: 'Electric trains run on high-efficiency steel rails and benefit from shared passenger capacity, yielding a footprint of just 0.03 kg CO2 per km, which is much lower than cars or flights.'
  }
];
